### ISSUE TITLE
Fix search route

### ISSUE THREAD

**Issue by infern018** [GeekHaven/weather-app#32] opened 2020-10-16 11:35 UTC
<img width="521" alt="search issue" src="https://user-images.githubusercontent.com/52378712/96253638-9d812480-0fd1-11eb-8a5c-97b0d338222d.png">

The search box in the search route is not working, most probably the problem is in any location component, figure it out and fix it

**Comment by Ranveer251** [comment] 2020-10-16 12:05
Please assign this to me

**Comment by garvitchittora** [comment] 2020-10-16 12:08
@Ranveer251 go ahead :)

**Comment by Ranveer251** [comment] 2020-10-17 10:36
I think the problem is with the api key. The limit of calls have been exceeded. **Status 429** ( too many requests ) is shown.

When I use my own api key then the search and home routes both are working fine.

![image](https://user-images.githubusercontent.com/53096435/96334859-7f7af900-1091-11eb-8917-ae70b05b630f.png)


However the displayed data (in the search route) can be brought a little bit down as it is kind of cluttering with the search area and a **more details** option can also be added in the data displayed in the search to view the full page info and graphs of the searched city.

Please let me know if these changes seem right to you and weather I can do them.

**Comment by garvitchittora** [comment] 2020-10-17 14:25
@Ranveer251 PR??

**Comment by Ranveer251** [comment] 2020-10-17 16:41
I am working on it.

**Closed as completed** 2020-10-19 07:41 UTC
Labels: bug, help wanted
